### ISSUE TITLE
Fail to detect NFTs

### ISSUE THREAD

**Issue by zmxv** [tondiamonds/tondiamonds#2]
### Bug Type

Functional

### Reproduction steps

1. Visit https://ton.diamonds/
2. Connect to Tonkeeper
3. Go to the profile page

### Actual result

No NFTs are shown.

<img width="628" alt="Screen Shot 2022-09-17 at 12 39 18 AM" src="https://user-images.githubusercontent.com/363061/190688112-eaf58ce7-43a7-40ef-959f-568edc7c2c49.png">

### Expected result

NFTs associated with the connected wallet address should be displayed as they are in Tonkeeper.

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: macOS
- Browser: Chrome
- Version: 105

Smartphone (please complete the following information):
- Device: iPhone 13 Pro
- OS: iOS 15.6.1
- Browser: Mobile Safari
- Version: Tonkeeper 2.6

**Comment by julialips** [comment]
The same
